### ISSUE TITLE
В проекте отсутcвует сам файл проекта .sln.

### ISSUE THREAD

**Issue by SergMarkof** [swerg/simple-lua-c-dll#2]
В проекте отсутcвует сам файл проекта .sln.

**Comment by swerg** [comment]
Это сделано сознательно. При открытии файла проекта .vcxproj файл .sln ("файл решения" в терминологии русской версии VS) создается автоматически, при этом .sln-файл не содержит каких-либо настроек.
Кроме того, формат .sln зависит от версии Visual Studio, а потому его хранение в репозитории создаст еще одну сущность поддержки и синхронизации нескольких версий файла для разных версий VS, что лишняя, но бесполезная рабта, т.к. см. первый абзац (и так создастся автоматически).

Итого: хранение .sln-файла в этом репозитории не планируется.
Достаточно .vcproj / .vcxproj файла.
